### ISSUE TITLE
Compositional pipelines

### ISSUE THREAD

**Issue by pbrisbin** [freckle/guides#28]
I'd like to get a guide in about the following variations currently present in our code-bases:

**A**

```hs
f . g $ h x
```

**B**

```hs
f . g . h $ x
```

**C**

```hs
f $ g $ h x
```

**D**

```hs
f $ g $ h $ x
```

I prefer **C**; I believe @jdreaver prefers **B**. Can others express an opinion so we can see where we stand? If you'd just prefer no guide, feel free to say that.

**Comment by pbrisbin** [comment]
To add some color for my own stance: I prefer **C** because I like to distinguish _compositional_ pipelines (`f . g . h`) from _application_ pipelines (`f $ g $ h x`). In other words, if an expression is pointful, it should be (simple) applications all the way, not an (unnecessary) applied composition, which is just a hair more complex to my brain. Totally subjective, but that's why.

**Comment by tfausak** [comment]
For some reason GitHub notifies me about new issues on this repo. And I can't help but comment on Haskell style questions 😆 

I like style A because it's tied for the fewest number of operators and I find `(.)` much easier to visually parse than `($)`. However it can be really annoying to refactor that style because changing the number of functions involved can require changing a few operators; looking at things from that angle, style C seems like the best choice.

**Comment by cdparks** [comment]
I prefer **C** now, but I used to prefer **E**

**E**

```haskell
f (g (h x))
```

Which probably means I can learn to prefer anything.

**Comment by cdparks** [comment]
> For some reason GitHub notifies me about new issues on this repo

hiiii @tfausak :wave:. I'm happy to see you chime in, but let us know if you want us to stop pinging you, should be easy to fix :stuck_out_tongue:

**Comment by tfausak** [comment]
Oh I'm sure I could find the setting to toggle, but I like these discussions. I've been trying to whittle away at our own style guide. Case in point: https://github.com/EdutainmentLIVE/haskell-style-guide/issues/37

**Comment by 5outh** [comment]
I prefer **A** (`f . g $ h x`)

- This uses the number of operators as **C**
- In general, I prefer function composition over application

I should also note that I don't mind if these styles are mixed. They're all acceptable to me (except **D**, but I think hlint will complain about that)

**Comment by jdreaver** [comment]
I use all of them depending on context and intent. I'm :-1: on having this in a style guide.

**Comment by pbrisbin** [comment]
I'm genuinely curious what intents/contexts would lead you to using either of these equivalent forms over others. Can you expand on that?

**Comment by jdreaver** [comment]
If I want something to feel "pipeline-y", like I'm doing a lot of complex operations in a row, I tend to use `.` a lot. If I just want to do a couple operations on something, like `head $ take 2 $ [1, 2, 3, 4]`, I might just use `$`.

To be honest I don't have a nice, consistent rule for when I use one or the other because I don't think about it too much. I've seen all of these styles used and I don't think any one of them really has an advantage over the others since it is pretty clear what is going on.

**Comment by pbrisbin** [comment]
> I don't think any one of them really has an advantage over the others

Just to be clear, no one is saying that's the case. It's just about consistency, and having a simple answer for people ramping up when they ask about how to write things.

**Comment by eborden** [comment]
I prefer **A**

**Comment by eborden** [comment]
Also a :-1: on a style guide for this.
